
FROM ubuntu:latest
# Installer isc-dhcp-client
RUN apt-get update && apt-get install -y \
 iptables iproute2 net-tools systemd telnet nano iputils-ping tcpdump \
 isc-dhcp-client \
 && apt-get clean


