services:
  client_a:
    build:
      context: ./client # Utiliser le Dockerfile dans dossier client
    container_name: client
    cap_add:
      - NET_ADMIN  # Ajoute la capacité pour manipuler le réseau
    networks: 
      - Reseaux1
    command: sleep infinity

  router:
    build:
      context: ./routeur # Utiliser le Dockerfile dans le dossier routeur
    container_name: router
    networks:
      Reseaux1:
        ipv4_address: 192.168.1.3
    command: sleep infinity
    cap_add:
      - NET_ADMIN  # Nécessaire pour activer le routage
    sysctls:
      - net.ipv4.ip_forward=1  # Activer le forwarding IP pour permettre le routage

networks:
  Reseaux1:
    driver: bridge  # Le driver est essentiel
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
  
