services:

  routeur_entreprise_primaire:
    image: routeur_frr
    container_name: routeur_entreprise_primaire
    networks:
      backbone_1:
        ipv4_address: "120.0.85.131"
    command: ["sh","/usr/local/bin/script.sh"]
    privileged: true
    volumes:
      - ./routeur_entreprise_primaire/script.sh:/usr/local/bin/script.sh
      - ./routeur_entreprise_primaire/daemons:/etc/frr/daemons
    cap_add:
      - NET_ADMIN  # Nécessaire pour activer le routage
    sysctls:
      - net.ipv4.ip_forward=1  # Activer le forwarding IP pour permettre le routage

  routeur_web_dns_secondaire:
    image: routeur_frr
    container_name: routeur_web_dns_secondaire
    networks:
      backbone_3:
        ipv4_address: "120.0.84.131"
        
      reseau_dns_web :
        ipv4_address : "120.0.83.5"   # interface vers serveur  WEB
        ipv4_address : "120.0.83.4"   #interface vers serveur DNS

    command: ["sh","/usr/local/bin/script.sh"]
    privileged: true
    volumes:
      - ./routeur_web_dns_secondaire/script.sh:/usr/local/bin/script.sh
      - ./routeur_web_dns_secondaire/daemons:/etc/frr/daemons
    cap_add:
      - NET_ADMIN  # Nécessaire pour activer le routage
    sysctls:
      - net.ipv4.ip_forward=1  # Activer le forwarding IP pour permettre le routage

  routeur_client:
    image: routeur_frr
    container_name: routeur_client
    networks:
      backbone_4:
        ipv4_address: "120.0.84.3"
    command: ["sh","/usr/local/bin/script.sh"]
    privileged: true
    volumes:
      - ./routeur_client/script.sh:/usr/local/bin/script.sh
      - ./routeur_client/daemons:/etc/frr/daemons
    cap_add:
      - NET_ADMIN  # Nécessaire pour activer le routage
    sysctls:
      - net.ipv4.ip_forward=1  # Activer le forwarding IP pour permettre le routage
      
  routeur_interconnexion:
    image: routeur_frr
    container_name: routeur_interconnexion
    networks:
      backbone_2:
        ipv4_address: "120.0.85.3"
    command: ["sh","/usr/local/bin/script.sh"]
    privileged: true
    volumes:
      - ./routeur_interconnexion/script.sh:/usr/local/bin/script.sh
      - ./routeur_interconnexion/daemons:/etc/frr/daemons
    cap_add:
      - NET_ADMIN  # Nécessaire pour activer le routage
    sysctls:
      - net.ipv4.ip_forward=1  # Activer le forwarding IP pour permettre le routage
      
  routeur_backbone:
    image: routeur_frr
    container_name: routeur_backbone
    networks:
      backbone_1:
        ipv4_address: "120.0.85.130"
      backbone_2:
        ipv4_address: "120.0.85.2"
      backbone_3:
        ipv4_address: "120.0.84.130"
      backbone_4:
        ipv4_address: "120.0.84.2"
    command: ["sh","/usr/local/bin/script.sh"]
    privileged: true
    volumes:
      - ./routeur_backbone/script.sh:/usr/local/bin/script.sh
      - ./routeur_backbone/daemons:/etc/frr/daemons
    cap_add:
      - NET_ADMIN  # Nécessaire pour activer le routage
    sysctls:
      - net.ipv4.ip_forward=1  # Activer le forwarding IP pour permettre le routage

  serveur_dns:
    build:
      context: ./dns # Utiliser le Dockerfile dans le dossier DNS
    container_name: serveur_dns
    networks:
      reseau_dns_web:
        ipv4_address: "120.0.83.3"
    command: ["sh","/usr/local/bin/script.sh"]
    privileged: true
    volumes:
      - ./dns/script.sh:/usr/local/bin/script.sh
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/named.conf.option:/etc/bind/named.conf.option
      - ./dns/zones/monsupersite.db:/etc/bind/zones/monsupersite.db
    cap_add:
      - NET_ADMIN  # Nécessaire pour activer le routage
    sysctls:
      - net.ipv4.ip_forward=1  # Activer le forwarding IP pour permettre le routage

  serveur_web:
    build:
      context: ./web # Utiliser le Dockerfile dans le dossier WEB
    container_name: serveur_web
    networks:
      reseau_dns_web:
        ipv4_address: "120.0.83.2"
    command: ["sh","/usr/local/bin/script.sh"]
    privileged: true
    volumes:
      - ./web/script.sh:/usr/local/bin/script.sh
      - ./web/index.html:/etc/www/index.html
      - ./web/style.css:/etc/www/css/style.css
    cap_add:
      - NET_ADMIN  # Nécessaire pour activer le routage
    sysctls:
      - net.ipv4.ip_forward=1  # Activer le forwarding IP pour permettre le routage


networks:
  backbone_1:
    driver: bridge  # Le driver est essentiel
    ipam:
      driver: default
      config:
        - subnet: "120.0.85.128/25"
  backbone_2:
    driver: bridge  # Le driver est essentiel
    ipam:
      driver: default
      config:
        - subnet: "120.0.85.0/25"
  backbone_3:
    driver: bridge  # Le driver est essentiel
    ipam:
      driver: default
      config:
        - subnet: "120.0.84.128/25"
  backbone_4:
    driver: bridge  # Le driver est essentiel
    ipam:
      driver: default
      config:
        - subnet: "120.0.84.0/25"
  reseau_dns_web:
    driver: bridge  # Le driver est essentiel
    ipam:
      driver: default
      config:
        - subnet: "120.0.83.0/25"

  
